restapi:
  api:
    version: v1.4.1
    releaseDate: "2023-05-29"
  edfapi:
    version: v3.4
    releaseDate: "1/5/2023"

server:
  address: 0.0.0.0
  port: 9112
  useTempFiles: true
  uploadTempPath: /tmp/
  uploadFilePath: /ems/app/simulation/custom/
  logPath: /ems/log
  firmwarePath: /tmp/
  firmwareName: firmware.bin
  emsConfigPath: /ems/etc/custom/
  emsConfigTempPath: /ems/app/configs/
  emsConfigExtEmsFileName: ext_ess/ext_ess-CUSTOM.xml
  emsConfigMeterFileName: meter/meter-CUSTOM.xml
  currentMode: production

log:
  level: error

api:
  endpoint: https://localhost
  GET: 18080
  POST: 18080
  PUT: 18080
  DELETE: 18080